// import fs from "fs";

// // Example names inspired by North and South Tripura regions
// // const tripuraNames = [
// //   "Arindam Das",
// //   "Rituparna Dey",
// //   "Subhendu Bhattacharjee",
// //   "Pranab Ghosh",
// //   "Mithun Debnath",
// //   "Anjana Paul",
// //   "Rajib Choudhury",
// //   "Srijita Saha",
// //   "Dipankar Dutta",
// //   "Rina Sarkar",
// //   "Debojit Nath",
// //   "Suchitra Sen",
// //   "Partha Barman",
// //   "Anupam Chakraborty",
// //   "Manish Deb",
// //   "Bikramjit Roy",
// //   "Sneha Biswas",
// //   "Raktim Pal",
// //   "Riya Dutta",
// //   "Sourav Debbarma",
// //   "Kaushik Bhattacharjee",
// //   "Ananya Ghosh",
// //   "Somnath Bhowmik",
// //   "Arpita Dasgupta",
// //   "Bishwajit Nath",
// //   "Payel Chowdhury",
// //   "Arindam Saha",
// //   "Preeti Ranjan",
// //   "Sujit Das",
// //   "Sampurna Choudhury",
// //   "Ranjan Chakraborty",
// //   "Rahul Sen",
// //   "Sayantan Sarkar",
// //   "Meenakshi Debnath",
// //   "Arnab Ghosh",
// //   "Nirmalya Roy",
// //   "Priyanka Das",
// //   "Avijit Bhowmik",
// //   "Sharmila Paul",
// //   "Rajashree Debbarma",
// //   "Pranjal Nath",
// //   "Chayanika Sen",
// //   "Anindita Roy",
// //   "Rupam Bhowmick",
// //   "Kaushiki Dutta",
// //   "Bibek Das",
// //   "Sudipta Choudhury",
// //   "Souradip Roy",
// //   "Mousumi Saha",
// //   "Pritam Das",
// //   "Manoj Debbarma",
// //   "Mriganka Nath",
// //   "Trina Sinha",
// //   "Subhajit Roy",
// //   "Ankita Debnath",
// //   "Sanjoy Dutta",
// //   "Anamika Chakraborty",
// //   "Aritra Sarkar",
// //   "Chiranjib Das",
// //   "Tanmay Ghosh",
// //   "Moumita Saha",
// //   "Kaushik Bhowmik",
// //   "Payel Paul",
// //   "Aniket Choudhury",
// //   "Shibashish Roy",
// //   "Sumana Sen",
// //   "Tamal Deb",
// //   "Sukanya Sarkar",
// //   "Rajnandini Nath",
// //   "Puja Choudhury",
// //   "Sourish Bhattacharjee",
// //   "Tithi Roy",
// //   "Rishabh Das",
// //   "Reshmi Dutta",
// //   "Prakash Choudhury",
// //   "Tanisha Das",
// //   "Ayan Debnath",
// //   "Suman Sarkar",
// //   "Debashree Nath",
// //   "Rahul Paul",
// //   "Sunanda Sen",
// //   "Pritam Roy",
// //   "Shrabanti Saha",
// //   "Sarthak Ghosh",
// //   "Piyali Bhowmik",
// //   "Debraj Das",
// //   "Amrita Paul",
// //   "Arjun Dutta",
// //   "Saikat Nath",
// //   "Poulami Das",
// //   "Sayan Debnath",
// //   "Abhishek Sen",
// //   "Debjani Choudhury",
// //   "Pradip Saha",
// //   "Aritra Bhattacharjee",
// //   "Sayani Das",
// // ];

// // Generate random clients
// // const clients = [];
// // let regNoCounter = 111; // Start from 111

// // for (let i = 0; i < 100; i++) {
// //   const name = tripuraNames[Math.floor(Math.random() * tripuraNames.length)];
// //   const email = `${name.toLowerCase().replace(/ /g, "")}${Math.floor(
// //     Math.random() * (983 - 11) + 11
// //   )}@gmail.com`;
// //   const amount =
// //     Math.floor(Math.random() * ((140000 - 60000) / 1000 + 1)) * 1000 + 60000;
// //   const interestRate = 15; // Random interest rate
// //   const duration = Math.floor(Math.random() * (36 - 12 + 1)) + 12; // Random duration

// //   clients.push({
// //     reg_no: `24ORTUS${regNoCounter}`, // Add registration number
// //     name,
// //     email,
// //     investment_type: "One-time",
// //     transactions: [
// //       {
// //         amount,
// //         interest_rate: parseFloat(interestRate.toFixed(1)),
// //         duration,
// //       },
// //     ],
// //   });

// //   regNoCounter++; // Increment the registration number
// // }

// // // Convert the clients array to a string with export syntax
// // const fileContent = `const clients = ${JSON.stringify(
// //   clients,
// //   null,
// //   2
// // )};\n\nexport default clients;`;

// // // Write to client.js file
// // fs.writeFile("customers.js", fileContent, (err) => {
// //   if (err) {
// //     console.error("Error writing to file:", err);
// //   } else {
// //     console.log("client.js file has been created successfully!");
// //   }
// // });

// // const fs = require("fs");

// // // Extended list of names inspired by North and South Tripura regions
// const tripuraNames = [
//   "Arindam Das",
//   "Rituparna Dey",
//   "Subhendu Bhattacharjee",
//   "Pranab Ghosh",
//   "Mithun Debnath",
//   "Anjana Paul",
//   "Rajib Choudhury",
//   "Srijita Saha",
//   "Dipankar Dutta",
//   "Rina Sarkar",
//   "Debojit Nath",
//   "Suchitra Sen",
//   "Partha Barman",
//   "Anupam Chakraborty",
//   "Manish Deb",
//   "Bikramjit Roy",
//   "Sneha Biswas",
//   "Raktim Pal",
//   "Riya Dutta",
//   "Sourav Debbarma",
//   "Kaushik Bhattacharjee",
//   "Ananya Ghosh",
//   "Somnath Bhowmik",
//   "Arpita Dasgupta",
//   "Bishwajit Nath",
//   "Payel Chowdhury",
//   "Arindam Saha",
//   "Preeti Ranjan",
//   "Sujit Das",
//   "Sampurna Choudhury",
//   "Ranjan Chakraborty",
//   "Rahul Sen",
//   "Sayantan Sarkar",
//   "Meenakshi Debnath",
//   "Arnab Ghosh",
//   "Nirmalya Roy",
//   "Priyanka Das",
//   "Avijit Bhowmik",
//   "Sharmila Paul",
//   "Rajashree Debbarma",
//   "Pranjal Nath",
//   "Chayanika Sen",
//   "Anindita Roy",
//   "Rupam Bhowmick",
//   "Kaushiki Dutta",
//   "Bibek Das",
//   "Sudipta Choudhury",
//   "Souradip Roy",
//   "Mousumi Saha",
//   "Pritam Das",
//   "Manoj Debbarma",
//   "Mriganka Nath",
//   "Trina Sinha",
//   "Subhajit Roy",
//   "Ankita Debnath",
//   "Sanjoy Dutta",
//   "Anamika Chakraborty",
//   "Aritra Sarkar",
//   "Chiranjib Das",
//   "Tanmay Ghosh",
//   "Moumita Saha",
//   "Kaushik Bhowmik",
//   "Payel Paul",
//   "Aniket Choudhury",
//   "Shibashish Roy",
//   "Sumana Sen",
//   "Tamal Deb",
//   "Sukanya Sarkar",
//   "Rajnandini Nath",
//   "Puja Choudhury",
//   "Sourish Bhattacharjee",
//   "Tithi Roy",
//   "Rishabh Das",
//   "Reshmi Dutta",
//   "Prakash Choudhury",
//   "Tanisha Das",
//   "Ayan Debnath",
//   "Suman Sarkar",
//   "Debashree Nath",
//   "Rahul Paul",
//   "Sunanda Sen",
//   "Pritam Roy",
//   "Shrabanti Saha",
//   "Sarthak Ghosh",
//   "Piyali Bhowmik",
//   "Debraj Das",
//   "Amrita Paul",
//   "Arjun Dutta",
//   "Saikat Nath",
//   "Poulami Das",
//   "Sayan Debnath",
//   "Abhishek Sen",
//   "Debjani Choudhury",
//   "Pradip Saha",
//   "Aritra Bhattacharjee",
//   "Sayani Das",
//   "Paromita Roy",
//   "Milan Debnath",
//   "Gaurav Saha",
//   "Puja Ghosh",
//   "Indrani Dutta",
//   "Prithviraj Nath",
//   "Siddharth Bhattacharjee",
//   "Meera Paul",
//   "Arjun Choudhury",
//   "Dipanwita Dey",
//   "Ranjit Das",
//   "Kalyan Sinha",
//   "Sucharita Bhowmik",
//   "Suvajit Dutta",
//   "Tanmay Roy",
//   "Sneha Dasgupta",
//   "Ritwik Bhattacharya",
//   "Sanjana Saha",
//   "Debarshi Nath",
//   "Manik Sarkar",
//   "Ritika Roy",
//   "Priyanka Sen",
//   "Arindam Dey",
//   "Siddhartha Debnath",
//   "Sankha Dutta",
//   "Ipsita Ghosh",
//   "Amrita Nath",
//   "Subrata Roy",
//   "Nabanita Saha",
//   "Abhirup Deb",
//   "Sonali Paul",
//   "Chayan Ghosh",
//   "Pritha Das",
//   "Rajat Sinha",
//   "Nilanjana Sarkar",
//   "Anindita Nath",
//   "Rajib Majumdar",
//   "Mrinmoy Bhattacharjee",
//   "Pratyasha Saha",
//   "Arpan Dutta",
//   "Rishita Debbarma",
//   "Sukriti Paul",
//   "Anindya Roy",
//   "Dipayan Nath",
//   "Sutapa Choudhury",
//   "Rupak Sarkar",
//   "Sayantani Bhowmik",
//   "Prantik Saha",
//   "Kaustav Bhattacharya",
//   "Purbasha Debnath",
//   "Ritwik Ghosh",
//   "Chayan Paul",
//   "Bidisha Dasgupta",
//   "Suvendu Barman",
//   "Reshma Dey",
//   "Prasun Dutta",
//   "Nupur Deb",
//   "Shreya Nath",
//   "Subhra Dey",
//   "Koustav Roy",
//   "Subhamita Saha",
//   "Kaushal Bhattacharjee",
//   "Anjana Choudhury",
//   "Torsha Debnath",
//   "Sushmita Paul",
//   "Kausturi Dutta",
//   "Subham Debbarma",
//   "Tamoghna Sarkar",
//   "Ipshita Sinha",
//   "Rimjhim Roy",
//   "Aratrika Saha",
//   "Jishnu Bhattacharya",
//   "Madhumita Ghosh",
//   "Dipanjan Nath",
//   "Priyasha Choudhury",
//   "Aparajita Das",
//   "Souren Deb",
//   "Rajib Bhowmik",
//   "Rinita Dutta",
//   "Nayan Dasgupta",
//   "Arpita Nath",
//   "Arghya Bhattacharya",
//   "Tiyasa Debbarma",
//   "Shinjini Ghosh",
//   "Rajkumar Deb",
//   "Deblina Saha",
//   "Sagnik Roy",
//   "Paromita Das",
//   "Somrita Bhowmik",
//   "Sreeparna Nath",
//   "Aranya Paul",
//   "Anubrata Deb",
//   "Payel Sinha",
//   "Jitendra Debnath",
//   "Madhurima Roy",
//   "Animesh Dutta",
//   "Soumya Bhowmik",
//   "Sanjib Sarkar",
//   "Ritaja Ghosh",
//   "Krishanu Debnath",
//   "Avijit Choudhury",
//   "Rimpa Das",
//   "Subhrajit Roy",
//   "Sayantika Bhattacharya",
//   "Suchismita Saha",
//   "Bikash Nath",
//   "Pritha Bhattacharjee",
//   "Ritoban Ghosh",
//   "Srijan Dutta",
//   "Srijita Sarkar",
//   "Sonamita Roy",
//   "Shanita Paul",
//   "Arnab Choudhury",
//   "Chinmoy Dey",
//   "Mou Saha",
//   "Rohit Deb",
//   "Pranati Bhowmik",
//   "Aradhana Roy",
//   "Niharika Das",
//   "Aditya Sarkar",
//   "Anupam Nath",
//   "Reshmi Choudhury",
//   "Dipti Paul",
//   "Avik Dutta",
//   "Rohini Bhowmik",
//   "Tapas Dasgupta",
//   "Nabendu Bhattacharya",
//   "Somnath Nath",
//   "Tanima Choudhury",
//   "Shristi Ghosh",
//   "Sayali Dutta",
//   "Biplab Roy",
//   "Smita Nath",
//   "Snehashish Deb",
//   "Supriya Saha",
//   "Rajdeep Choudhury",
// ];

// // Generate random SIP clients
// const sipClients = [];
// let sipRegNoCounter = 211; // Start from 211
// for (let i = 0; i < 200; i++) {
//   const name = tripuraNames[Math.floor(Math.random() * tripuraNames.length)];
//   const email = `${name.toLowerCase().replace(/ /g, "")}${Math.floor(
//     Math.random() * (Math.floor(983) - Math.ceil(11)) + Math.ceil(11)
//   )}@gmail.com`;
//   const amount =
//     Math.floor(Math.random() * ((40000 - 20000) / 5000 + 1)) * 5000 + 20000;
//   const interestRate = 12; // Random interest rate between 6.0% and 8.0%
//   const duration = Math.floor(Math.random() * (60 - 12 + 1)) + 12; // Random duration between 12 and 60 months

//   sipClients.push({
//     reg_no: `24ORTUS${sipRegNoCounter}`, // Add registration number
//     name,
//     email,
//     investment_type: "SIP",
//     transactions: [
//       {
//         amount,
//         interest_rate: parseFloat(interestRate.toFixed(1)),
//         duration,
//       },
//     ],
//   });
//   sipRegNoCounter++; // Increment the registration number
// }

// // Convert the SIP clients array to a string with export syntax
// const fileContent = `const clients = ${JSON.stringify(
//   sipClients,
//   null,
//   2
// )};\n\nexport default clients;`;

// // Write to client.js file
// fs.writeFile("client2.js", fileContent, (err) => {
//   if (err) {
//     console.error("Error writing to file:", err);
//   } else {
//     console.log(
//       "client.js file has been created successfully with 200 SIP clients!"
//     );
//   }
// });
